spring.application.name=manager

# Dados de Conexão (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5433/barbershop_db
spring.datasource.username=lucas_barroso
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

api.security.token.secret=TokenChaveLouca